// Compiles MDX sources into TypeScript modules:
//   blogs/<locale>/*.mdx          -> data/blogs.generated.ts
//   content/<page>/<locale>.mdx   -> data/pages.generated.ts
//
// The app runs on Cloudflare Workers, where there is no project filesystem at
// request time. Reading these with fs yielded nothing in production: every blog
// article 404'd, and about / privacy-policy / terms-of-service fed an empty
// string to MDXRemote and returned HTTP 500. Inlining at build time removes the
// runtime fs dependency entirely.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import matter from 'gray-matter';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const BLOGS_DIR = path.join(ROOT, 'blogs');
const CONTENT_DIR = path.join(ROOT, 'content');
const BLOGS_OUT = path.join(ROOT, 'data', 'blogs.generated.ts');
const PAGES_OUT = path.join(ROOT, 'data', 'pages.generated.ts');
const DEFAULT_PAGE_LOCALE = 'en';

function toDateString(value) {
  if (value instanceof Date) return value.toISOString();
  if (typeof value === 'string' && value.trim()) return new Date(value).toISOString();
  return new Date(0).toISOString();
}

function normalizeSlug(raw, filename) {
  const fallback = filename.replace(/\.mdx?$/, '').replace(/^\d+\./, '');
  const slug = (raw || fallback).trim();
  return slug.startsWith('/') ? slug : `/${slug}`;
}

function readLocale(locale) {
  const dir = path.join(BLOGS_DIR, locale);
  return fs
    .readdirSync(dir)
    .filter((f) => /\.mdx?$/.test(f))
    .map((filename) => {
      const { data, content } = matter(fs.readFileSync(path.join(dir, filename), 'utf8'));

      if (!data.title) throw new Error(`${locale}/${filename}: missing "title" in frontmatter`);

      return {
        locale,
        title: data.title,
        description: data.description || '',
        image: data.image || '',
        slug: normalizeSlug(data.slug, filename),
        tags: data.tags || '',
        date: toDateString(data.date),
        visible: data.visible || 'published',
        pin: Boolean(data.pin),
        content,
        metadata: { ...data, date: toDateString(data.date) },
      };
    });
}

const locales = fs
  .readdirSync(BLOGS_DIR, { withFileTypes: true })
  .filter((e) => e.isDirectory())
  .map((e) => e.name);

const byLocale = {};
let total = 0;

for (const locale of locales) {
  const posts = readLocale(locale);

  const seen = new Set();
  for (const post of posts) {
    if (seen.has(post.slug)) throw new Error(`${locale}: duplicate slug "${post.slug}"`);
    seen.add(post.slug);
  }

  byLocale[locale] = posts;
  total += posts.length;
  console.log(`  ${locale}: ${posts.length} post(s)`);
}

const blogsBanner = `// AUTO-GENERATED by scripts/build-content.mjs — do not edit by hand.
// Source of truth is blogs/<locale>/*.mdx. Regenerate with: pnpm run build:content
//
// Inlined at build time because Cloudflare Workers has no filesystem at runtime.

import type { RawBlogPost } from '@/types/blog'

export const BLOG_POSTS: Record<string, RawBlogPost[]> = `;

fs.writeFileSync(BLOGS_OUT, `${blogsBanner}${JSON.stringify(byLocale, null, 2)}\n`, 'utf8');
console.log(`build-content: wrote ${total} post(s) to data/blogs.generated.ts`);

/* ------------------------------------------------------------------ */
/*  Static pages (about / privacy-policy / terms-of-service)           */
/* ------------------------------------------------------------------ */

// AdSense requires a reachable privacy policy, so a build that cannot find
// these should fail loudly rather than ship another 500.
const REQUIRED_PAGES = ['about', 'privacy-policy', 'terms-of-service'];

const pageSlugs = fs
  .readdirSync(CONTENT_DIR, { withFileTypes: true })
  .filter((e) => e.isDirectory())
  .map((e) => e.name);

const pages = {};
let pageCount = 0;

for (const slug of pageSlugs) {
  const dir = path.join(CONTENT_DIR, slug);
  const byLoc = {};

  for (const filename of fs.readdirSync(dir).filter((f) => /\.mdx?$/.test(f))) {
    const locale = filename.replace(/\.mdx?$/, '');
    const { data, content } = matter(fs.readFileSync(path.join(dir, filename), 'utf8'));

    if (!content.trim()) throw new Error(`content/${slug}/${filename}: body is empty`);

    byLoc[locale] = {
      title: data.title || '',
      description: data.description || '',
      content,
    };
    pageCount += 1;
  }

  pages[slug] = byLoc;
  console.log(`  ${slug}: ${Object.keys(byLoc).join(', ')}`);
}

for (const slug of REQUIRED_PAGES) {
  if (!pages[slug]?.[DEFAULT_PAGE_LOCALE]) {
    throw new Error(
      `content/${slug}/${DEFAULT_PAGE_LOCALE}.mdx is missing — that page would 500 in production`
    );
  }
}

const pagesBanner = `// AUTO-GENERATED by scripts/build-content.mjs — do not edit by hand.
// Source of truth is content/<page>/<locale>.mdx. Regenerate with: pnpm run build:content
//
// Inlined at build time because Cloudflare Workers has no filesystem at runtime.

export interface StaticPage {
  title: string
  description: string
  content: string
}

export const STATIC_PAGES: Record<string, Record<string, StaticPage>> = `;

fs.writeFileSync(PAGES_OUT, `${pagesBanner}${JSON.stringify(pages, null, 2)}\n`, 'utf8');
console.log(`build-content: wrote ${pageCount} page(s) to data/pages.generated.ts`);
