// Compiles blogs/<locale>/*.mdx into data/blogs.generated.ts.
//
// The app runs on Cloudflare Workers, where there is no project filesystem at
// request time — reading blogs/ with fs silently yielded zero posts, which is
// why every article 404'd. Inlining the content at build time removes the
// runtime fs dependency entirely.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import matter from 'gray-matter';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const BLOGS_DIR = path.join(ROOT, 'blogs');
const OUT_FILE = path.join(ROOT, 'data', 'blogs.generated.ts');

function toDateString(value) {
  if (value instanceof Date) return value.toISOString();
  if (typeof value === 'string' && value.trim()) return new Date(value).toISOString();
  return new Date(0).toISOString();
}

function normalizeSlug(raw, filename) {
  const fallback = filename.replace(/\.mdx?$/, '').replace(/^\d+\./, '');
  const slug = (raw || fallback).trim();
  return slug.startsWith('/') ? slug : `/${slug}`;
}

function readLocale(locale) {
  const dir = path.join(BLOGS_DIR, locale);
  return fs
    .readdirSync(dir)
    .filter((f) => /\.mdx?$/.test(f))
    .map((filename) => {
      const { data, content } = matter(fs.readFileSync(path.join(dir, filename), 'utf8'));

      if (!data.title) throw new Error(`${locale}/${filename}: missing "title" in frontmatter`);

      return {
        locale,
        title: data.title,
        description: data.description || '',
        image: data.image || '',
        slug: normalizeSlug(data.slug, filename),
        tags: data.tags || '',
        date: toDateString(data.date),
        visible: data.visible || 'published',
        pin: Boolean(data.pin),
        content,
        metadata: { ...data, date: toDateString(data.date) },
      };
    });
}

const locales = fs
  .readdirSync(BLOGS_DIR, { withFileTypes: true })
  .filter((e) => e.isDirectory())
  .map((e) => e.name);

const byLocale = {};
let total = 0;

for (const locale of locales) {
  const posts = readLocale(locale);

  const seen = new Set();
  for (const post of posts) {
    if (seen.has(post.slug)) throw new Error(`${locale}: duplicate slug "${post.slug}"`);
    seen.add(post.slug);
  }

  byLocale[locale] = posts;
  total += posts.length;
  console.log(`  ${locale}: ${posts.length} post(s)`);
}

const banner = `// AUTO-GENERATED by scripts/build-blogs.mjs — do not edit by hand.
// Source of truth is blogs/<locale>/*.mdx. Regenerate with: pnpm run build:blogs
//
// Inlined at build time because Cloudflare Workers has no filesystem at runtime.

import type { RawBlogPost } from '@/types/blog'

export const BLOG_POSTS: Record<string, RawBlogPost[]> = `;

fs.writeFileSync(OUT_FILE, `${banner}${JSON.stringify(byLocale, null, 2)}\n`, 'utf8');
console.log(`build-blogs: wrote ${total} post(s) to data/blogs.generated.ts`);
